import React from 'react';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';
import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar"
import SettingsIcon from '@mui/icons-material/Settings';
import { Navbar } from '@/components/ui/navbar';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};



// Layout Raiz com Navbar
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={inter.className}>
        <Navbar /> 
        {children}
      </body>
    </html>
  );
}
