import React from 'react';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';
import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import SettingsIcon from '@mui/icons-material/Settings';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


// Componente Navbar
const Navbar = () => {
  return (
    <nav style={{ background: 'pink', color: 'white', padding: '1rem', height: '70px', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
      <div style={{ display: 'flex', justifyContent: 'space-around', alignItems: 'center', width: '100%' }}>
        <ul style={{ listStyle: 'none', display: 'flex', flexGrow: 1, justifyContent: 'space-around' }}>
        <Avatar>
          <AvatarImage src="https://yt3.googleusercontent.com/ytc/AIf8zZStzt_Grffe61uO_793ShkNFr29Q0Fg0ppwBw_53A=s900-c-k-c0x00ffffff-no-rj" />
          <AvatarFallback>iti</AvatarFallback>
        </Avatar>

        </ul>
        <h1 style={{ color: 'black', fontSize: '24px', margin: 0 }}>Newsletter</h1> 
        <ul style={{ listStyle: 'none', display: 'flex', flexGrow: 1, justifyContent: 'space-around' }}>
        <DropdownMenu>
          <DropdownMenuTrigger>
            <SettingsIcon />
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuLabel>Minha conta</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Perfil</DropdownMenuItem>
            <DropdownMenuItem>Sair</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>

        </ul>
      </div>
    </nav>
  );
};


// Layout Raiz com Navbar
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={inter.className}>
        <Navbar /> 
        {children}
      </body>
    </html>
  );
}
